#!/bin/bash

afficher_synopsis() {
    echo -e "Utilisation : $0 -u <utilisateur>" >&2
}

file="/etc/passwd"

if [[ $# -eq 0 ]]; then
    while read -r line; do
        uid=$(cut -d: -f3 <<<"$line")
        if [[ "$uid" -ge 1000 ]]; then
            nom=$(cut -d: -f1 <<<"$line")
            shell=$(cut -d: -f7 <<<"$line") 
            echo -e "${nom} : ${shell}"
        fi
    done < "$file"
    exit 0
fi

while getopts "u:" opt; do
    case $opt in
    u)
        user="${OPTARG}"
        user_line=$(grep "^${user}:" "$file")

        if [[ -z "${user_line}" ]]; then
            echo -e "Utilisateur inexistant"
            exit 2
        fi

        user_uid=$(cut -d: -f3 <<< "$user_line")
        user_shell=$(cut -d: -f7 <<< "$user_line")

        if [[ "${user_uid}" -lt 1000 ]]; then
            echo -e "Erreur : l'utilisateur ${user} (UID ${user_uid}) est un compte système"
            exit 3

        else
            echo -e "Shell par défaut de l'utilisateur ${user} : ${user_shell}"
        fi
        ;;
    *)
        afficher_synopsis
        exit 1
        ;;
    esac
done
exit 0
